version : "3"
services: 
    api:
        build: .
        image: my_blog_server-api:v1.0
        depends_on:
            - postgres
        ports:
          - 8000:8000
        volumes:
          - ./:/usr/src/app:rw
        command: sh -c "alembic upgrade head & \
                        python ./app/main.py & \
                        python ./app/services/user_auth_service/auth_micro.py & \
                        python ./app/services/post_service/post_micro.py & \
                        python ./app/services/comments_service/comments_micro.py & \
                        wait"
        env_file:
          - .env
    postgres:
      image: postgres
      ports:
        - 5432:5432
      restart: always
      environment:
        - POSTGRES_USER=postgres 
        - POSTGRES_PASSWORD=0000
        - POSTGRES_DB=blogdb

      volumes:
        - postgres-db:/var/lib/postgresql/data

    adminer:
      image: adminer
      restart: always
      depends_on:
        - postgres
      ports:
        - 8080:8080

volumes:
    postgres-db: