"""add_image_column_in_post_table

Revision ID: cce5a16aa469
Revises: 72f72f742222
Create Date: 2023-04-04 16:37:22.009003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce5a16aa469'
down_revision = '72f72f742222'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('group_id', sa.String(), nullable=True, default='none'),)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'group_id')
    # ### end Alembic commands ###
